spring.application.name=url-shortener
spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener
spring.datasource.username=urlshortener
spring.datasource.password=urlshortener
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect